### ISSUE TITLE
FQ: Markdown support

### ISSUE THREAD

**Issue by madsem** [outl1ne/nova-notes-field#16]
Hey @Tarpsvo , cool package thanks for that :)

Wanted to throw in the mix: It would actually be cool if the `NotesField` would (maybe optionally) use the `MarkDown` field.
 Thoughts?

**Comment by Tarpsvo** [comment]
We already have the option of using the Trix field, but we currently do not offer the option of markdown field. However, it would indeed be useful. ;)

![image](https://user-images.githubusercontent.com/2018660/220851433-3f1fb9e7-1231-4d01-947f-b38680d4302a.png)

**Comment by richard-raadi** [comment]
Hey @madsem 
We are happy to review pull requests and merge them after testing!
