### ISSUE TITLE
Ignore scopes

### ISSUE THREAD

**Issue by RomkaLTU** [outl1ne/nova-notes-field#32]
Is there any way to ignore scopes? For example, I have global scope "where published == true" but still want to be able to add comments, because this status only hides the model from the frontend.

**Comment by Tarpsvo** [comment]
Hi! Can you elaborate a bit please? Ie how'd you add the scope in the first place?

Theoretically you can overwrite the HasNotes' traits notes() method and remove scopes there:

```
public function notes()
    {
        return $this->morphMany(NotesFieldServiceProvider::getNotesModel(), 'notable')->withoutGlobalScopes();
    }
```
