### ISSUE TITLE
Support for Nova 4

### ISSUE THREAD

**Issue by joostvanhoof** [outl1ne/nova-notes-field#46]
Not sure if this package is actively maintained. But would be nice to have Nova 4 support now that it's out. @Tarpsvo

**Comment by vesper8** [comment]
Several forks have implemented support for Nova 4

I had a look at a few of them and this one is the one I went with https://github.com/joostvanhoof/nova-notes-field

**Comment by Tarpsvo** [comment]
Nova 4 support added in version 3.0.0.
