### ISSUE TITLE
Editing existing Notes

### ISSUE THREAD

**Issue by andrewgoodnz** [outl1ne/nova-notes-field#60]
I would like to be able to edit existing notes. Is there a process available to enable this?

**Comment by steven-fox** [comment]
I'll see if I can make this work and submit a PR.

I'm thinking we'll make it so that the authors of a note can edit it but others can't. Similar to the "delete" authorization already in place. Furthermore, system notes will be uneditable. 👍

**Comment by andrewgoodnz** [comment]
Thanks @steven-fox! Just tested your PR and works perfectly!

**Comment by steven-fox** [comment]
@andrewgoodnz Excellent! Hopefully the package maintainer can review, merge, and tag a new release soon.

If you happen to be the person that created an Upwork posting for this feature, please take a glance at my proposal. 🙂
