### ISSUE TITLE
[Error] Failed to load resource: the server responded with a status of 404 () (notes, line 0)

### ISSUE THREAD

**Issue by renege** [outl1ne/nova-notes-field#62]
Hi 
Using latest version with Nova 4 and L10, and getting 404 for some reason. Worked fine before.

<img width="1074" alt="Scherm­afbeelding 2023-06-07 om 12 01 28" src="https://github.com/outl1ne/nova-notes-field/assets/2900069/6f672748-2705-47c1-824f-3c44d0830655">

**Comment by Jaspur** [comment]
Same issue here

**Comment by eugenl1nde** [comment]
Hey!

Doesn't reproduce in Laravel 10.18.0 and Nova 4.27.10.
Did you update your Nova from 3 to 4? Or does it still reproduce?

Additional details would be good in order to reproduce.

**Comment by richard-raadi** [comment]
Closing stale issue.
